defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent

name: ${env}_pre_diffusion_unet_ta${horizon_steps}_td${denoising_steps}
logdir: /home/qxy/DMLoco/log/aliengo-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: /home/qxy/DMLoco/data/aliengo/forward_1.0_50.npz

seed: 42
device: cuda:0
env: aliengo
obs_dim: 392
action_dim: 12
denoising_steps: 100
horizon_steps: 4
cond_steps: 1

wandb:
  entity: queenxy2002
  project: aliengo-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 10000
  batch_size: 256
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 10000
    warmup_steps: 100
    min_lr: 1e-5
  train_split: 0.1
  epoch_start_ema: 20
  update_ema_freq: 10
  save_model_freq: 500
  val_freq: 100
  log_freq: 10

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.unet.Unet1D
    diffusion_step_embed_dim: 16
    dim: 64
    dim_mults: [1, 2, 4]
    kernel_size: 5
    n_groups: 8
    smaller_encoder: False
    cond_mlp_dims: [512, 128]
    cond_predict_scale: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    action_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}